[package]
name = "leg_fs"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.60", features = ["derive"] }
logic-expression-generator = { path = "../" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
