[lib]
name = "logic_expression_generator"
crate-type = ["cdylib"]

[package]
name = "logic-expression-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
pyo3 = { version = "0.28.2", features = ["abi3-py38"] }
rand = "0.10.0"
